# syntax=docker/dockerfile:1

FROM rust:1.61-slim-bullseye AS builder
LABEL maintainer="ckatsak@gmail.com"

RUN apt-get update && apt-get -y install make pkg-config libclang-dev curl \
	&& cargo install bindgen \
	&& rustup component add rustfmt

ADD . /libhwloc2-rs

RUN curl -LO https://download.open-mpi.org/release/hwloc/v2.7/hwloc-2.7.1.tar.gz \
	&& tar -xzf hwloc-2.7.1.tar.gz \
	&& cd /hwloc-2.7.1/ \
	&& ./configure --prefix=/usr --disable-cairo --disable-libxml2 --disable-io --disable-pci \
		--disable-opencl --disable-cuda --disable-nvml --disable-rsmi --disable-levelzero \
		--disable-gl --disable-libudev --disable-plugin-dlopen --disable-plugin-ltdl \
	&& make -j$(nproc) \
	&& make install \
	&& cd /libhwloc2-rs/hwloc2-sys \
	&& bindgen --generate-inline-functions --allowlist-function '.*hwloc.*' \
		--allowlist-type '.*hwloc.*' --allowlist-var '(.*hwloc.*|.*HWLOC.*)' \
		-o src/bindings.rs /usr/include/hwloc.h -- -I/usr/include/hwloc/ \
	&& cd /libhwloc2-rs \
	&& cargo t --workspace -- --nocapture \
	&& cargo b --release --example print_all \
	&& strip -s /libhwloc2-rs/target/release/examples/print_all


FROM gcr.io/distroless/base-debian11

COPY --from=builder /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/x86_64-linux-gnu/
COPY --from=builder /usr/lib/libhwloc.so.15.5.3 /usr/lib/libhwloc.so.15
COPY --from=builder /libhwloc2-rs/target/release/examples/print_all /

CMD ["/print_all"]

# Build:
# 	$ docker build --progress=plain --no-cache --pull \
# 		-f Dockerfile_example -t ckatsak/hwloc:example .
# Run:
# 	$ docker run --rm -it ckatsak/hwloc:example
